import { NextResponse } from 'next/server';

// Import mock products from the main products route
const mockProducts = [
  {
    id: '1',
    sku: 'SILK-001',
    title: 'Luxe Silk Charmeuse',
    description: 'Experience the epitome of luxury with our premium Italian Silk Charmeuse. This exquisite 100% pure silk fabric features an incredibly smooth texture with a lustrous satin finish on one side and a soft matte finish on the reverse. With a lightweight 80 GSM and elegant drape, it flows beautifully making it the perfect choice for evening gowns, bridal wear, luxury lingerie, and high-end garments. The superior sheen and exceptional color vibrancy make every piece a masterpiece. Sourced directly from Italy\'s finest silk mills, this fabric embodies timeless elegance and sophistication.',
    vendor: 'Italian Textiles Co.',
    collection: 'Silk',
    material: 'Silk',
    gsm: 80,
    width: 140,
    colorways: [
      { id: '1', name: 'Champagne Gold', hex: '#c89116' },
      { id: '2', name: 'Midnight Navy', hex: '#1a1a2e' },
      { id: '3', name: 'Ruby Wine', hex: '#8b1538' },
    ],
    care: ['dry-clean', 'cool-iron', 'no-bleach', 'no-tumble-dry'],
    countryOfOrigin: 'Italy',
    unitLengthOptions: [
      { unit: 'meter', minLength: 0.5, maxLength: 10, increment: 0.5 },
      { unit: 'yard', minLength: 0.5, maxLength: 11, increment: 0.5 },
    ],
    price: 899,
    compareAtPrice: 1199,
    images: [
      {
        id: '1',
        url: '/images/products/silk-charmeuse.jpg',
        alt: 'Luxe Silk Charmeuse Fabric',
        width: 1200,
        height: 1600,
      },
    ],
    variants: [
      {
        id: '1',
        sku: 'SILK-001-GOLD',
        title: 'Champagne Gold',
        colorway: { id: '1', name: 'Champagne Gold', hex: '#c89116' },
        price: 899,
        compareAtPrice: 1199,
        stockQuantity: 30,
        availability: 'in_stock',
      },
      {
        id: '2',
        sku: 'SILK-001-NAVY',
        title: 'Midnight Navy',
        colorway: { id: '2', name: 'Midnight Navy', hex: '#1a1a2e' },
        price: 899,
        compareAtPrice: 1199,
        stockQuantity: 25,
        availability: 'in_stock',
      },
      {
        id: '3',
        sku: 'SILK-001-WINE',
        title: 'Ruby Wine',
        colorway: { id: '3', name: 'Ruby Wine', hex: '#8b1538' },
        price: 899,
        compareAtPrice: 1199,
        stockQuantity: 20,
        availability: 'in_stock',
      },
    ],
    tags: ['luxury', 'silk', 'italian', 'bestseller'],
    certifications: ['OEKO-TEX Standard 100'],
    availability: 'in_stock',
    stockQuantity: 30,
    badge: null,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-20',
  },
  {
    id: '2',
    sku: 'COTTON-002',
    title: 'Premium Organic Cotton',
    description: 'Discover the perfect blend of comfort and sustainability with our Premium Organic Cotton fabric. GOTS certified and ethically sourced from India\'s finest organic farms, this 100% pure cotton features a medium 120 GSM weight that\'s ideal for year-round wear. The natural breathability and exceptional softness make it perfect for everyday clothing, children\'s wear, bedding, and home textiles. Pre-washed for minimal shrinkage and enhanced softness, this fabric maintains its shape and color through countless washes. The tight weave ensures durability while the natural fibers remain gentle on sensitive skin. Choose eco-conscious luxury without compromising on quality.',
    vendor: 'EcoFabrics Ltd.',
    collection: 'Cotton',
    material: 'Cotton',
    gsm: 120,
    width: 150,
    colorways: [
      { id: '4', name: 'Natural White', hex: '#f8f8f0' },
      { id: '5', name: 'Sage Green', hex: '#9caf88' },
      { id: '6', name: 'Terracotta', hex: '#cc8b65' },
    ],
    care: ['machine-wash', 'tumble-dry-low', 'warm-iron', 'no-bleach'],
    countryOfOrigin: 'India',
    unitLengthOptions: [
      { unit: 'meter', minLength: 1, maxLength: 20, increment: 1 },
      { unit: 'yard', minLength: 1, maxLength: 22, increment: 1 },
    ],
    price: 499,
    compareAtPrice: 699,
    images: [
      {
        id: '2',
        url: '/images/products/organic-cotton.jpg',
        alt: 'Premium Organic Cotton Fabric',
        width: 1200,
        height: 1600,
      },
    ],
    variants: [
      {
        id: '4',
        sku: 'COTTON-002-WHITE',
        title: 'Natural White',
        colorway: { id: '4', name: 'Natural White', hex: '#f8f8f0' },
        price: 499,
        compareAtPrice: 699,
        stockQuantity: 50,
        availability: 'in_stock',
      },
      {
        id: '5',
        sku: 'COTTON-002-GREEN',
        title: 'Sage Green',
        colorway: { id: '5', name: 'Sage Green', hex: '#9caf88' },
        price: 499,
        compareAtPrice: 699,
        stockQuantity: 40,
        availability: 'in_stock',
      },
    ],
    tags: ['organic', 'cotton', 'sustainable', 'eco-friendly'],
    certifications: ['GOTS Certified'],
    availability: 'in_stock',
    stockQuantity: 50,
    badge: null,
    createdAt: '2024-01-16',
    updatedAt: '2024-01-21',
  },
  {
    id: '3',
    sku: 'VELVET-003',
    title: 'Royal Velvet',
    description: 'Indulge in the opulence of our Royal Velvet, a heavyweight luxury fabric that exudes elegance and sophistication. Imported from France, this premium velvet features a rich, dense pile with exceptional depth of color and a sumptuous soft-touch finish. The 300 GSM weight provides substantial body while maintaining graceful drape, making it ideal for premium upholstery, statement curtains, luxury cushions, and high-end fashion pieces. The tightly woven backing ensures durability and stability, while the plush pile surface offers unparalleled tactile luxury. Available in jewel-tone colors that catch and reflect light beautifully, creating an ever-changing visual appeal. Perfect for adding a touch of regal elegance to any space or wardrobe.',
    vendor: 'Royal Fabrics Inc.',
    collection: 'Velvet',
    material: 'Velvet',
    gsm: 300,
    width: 140,
    colorways: [
      { id: '7', name: 'Emerald Green', hex: '#046307' },
      { id: '8', name: 'Royal Blue', hex: '#002366' },
      { id: '9', name: 'Burgundy', hex: '#800020' },
    ],
    care: ['dry-clean-only', 'no-iron', 'no-bleach', 'no-tumble-dry'],
    countryOfOrigin: 'France',
    unitLengthOptions: [
      { unit: 'meter', minLength: 0.5, maxLength: 10, increment: 0.5 },
      { unit: 'yard', minLength: 0.5, maxLength: 11, increment: 0.5 },
    ],
    price: 799,
    compareAtPrice: 999,
    images: [
      {
        id: '3',
        url: '/images/products/royal-velvet.jpg',
        alt: 'Royal Velvet Fabric',
        width: 1200,
        height: 1600,
      },
    ],
    variants: [
      {
        id: '6',
        sku: 'VELVET-003-EMERALD',
        title: 'Emerald Green',
        colorway: { id: '7', name: 'Emerald Green', hex: '#046307' },
        price: 799,
        compareAtPrice: 999,
        stockQuantity: 15,
        availability: 'in_stock',
      },
      {
        id: '7',
        sku: 'VELVET-003-BLUE',
        title: 'Royal Blue',
        colorway: { id: '8', name: 'Royal Blue', hex: '#002366' },
        price: 799,
        compareAtPrice: 999,
        stockQuantity: 12,
        availability: 'in_stock',
      },
    ],
    tags: ['luxury', 'velvet', 'french', 'upholstery'],
    certifications: ['OEKO-TEX Standard 100'],
    availability: 'in_stock',
    stockQuantity: 15,
    badge: null,
    createdAt: '2024-01-17',
    updatedAt: '2024-01-22',
  },
  {
    id: '4',
    sku: 'JACQUARD-004',
    title: 'Heritage Jacquard Weave',
    description: 'Celebrate the rich heritage of Indian textile artistry with our exquisite Jacquard Weave fabric. This masterpiece features intricate traditional motifs woven using time-honored jacquard techniques, creating stunning raised patterns that add depth and texture. Crafted from premium silk blend, this 180 GSM fabric combines the luxurious sheen of silk with enhanced durability. Perfect for festive ethnic wear, ceremonial garments, bridal lehengas, sherwanis, and special occasion outfits. The reversible weave pattern offers versatility in design, while the rich metallic threads woven throughout add a touch of opulence. Each meter tells a story of skilled craftsmanship passed down through generations. Handloom Mark certified, supporting traditional Indian weavers.',
    vendor: 'Heritage Textiles',
    collection: 'Festive',
    material: 'Silk Blend',
    gsm: 180,
    width: 110,
    colorways: [
      { id: '10', name: 'Gold & Maroon', hex: '#b8860b' },
      { id: '11', name: 'Silver & Navy', hex: '#c0c0c0' },
    ],
    care: ['dry-clean', 'cool-iron', 'no-bleach', 'no-tumble-dry'],
    countryOfOrigin: 'India',
    unitLengthOptions: [
      { unit: 'meter', minLength: 1, maxLength: 10, increment: 0.5 },
      { unit: 'yard', minLength: 1, maxLength: 11, increment: 0.5 },
    ],
    price: 649,
    compareAtPrice: 899,
    images: [
      {
        id: '4',
        url: '/images/products/jacquard-weave.jpg',
        alt: 'Heritage Jacquard Weave Fabric',
        width: 1200,
        height: 1600,
      },
    ],
    variants: [
      {
        id: '8',
        sku: 'JACQUARD-004-GOLD',
        title: 'Gold & Maroon',
        colorway: { id: '10', name: 'Gold & Maroon', hex: '#b8860b' },
        price: 649,
        compareAtPrice: 899,
        stockQuantity: 20,
        availability: 'in_stock',
      },
    ],
    tags: ['festive', 'jacquard', 'traditional', 'ethnic'],
    certifications: ['Handloom Mark'],
    availability: 'in_stock',
    stockQuantity: 20,
    badge: null,
    createdAt: '2024-01-18',
    updatedAt: '2024-01-23',
  },
  {
    id: '5',
    sku: 'LINEN-005',
    title: 'Belgian Linen',
    description: 'Experience the timeless elegance of our Premium Belgian Linen, sourced from Europe\'s finest flax fields. This 100% pure linen fabric features the characteristic natural slub texture that becomes softer and more beautiful with each wash. The medium 180 GSM weight strikes the perfect balance between durability and breathability, making it ideal for summer clothing, lightweight curtains, table linens, and sustainable fashion. Naturally temperature-regulating, this fabric keeps you cool in summer and warm in winter. The subtle natural variations in the weave add authentic charm and character. Pre-washed to minimize shrinkage and enhance the signature relaxed drape. OEKO-TEX certified for safety and environmental responsibility. A sustainable choice that ages gracefully and lasts for generations.',
    vendor: 'European Linens',
    collection: 'Linen',
    material: 'Linen',
    gsm: 180,
    width: 150,
    colorways: [
      { id: '12', name: 'Natural Beige', hex: '#d2b48c' },
      { id: '13', name: 'Soft Gray', hex: '#9e9e9e' },
    ],
    care: ['machine-wash', 'tumble-dry-low', 'warm-iron', 'no-bleach'],
    countryOfOrigin: 'Belgium',
    unitLengthOptions: [
      { unit: 'meter', minLength: 1, maxLength: 15, increment: 0.5 },
      { unit: 'yard', minLength: 1, maxLength: 16, increment: 0.5 },
    ],
    price: 599,
    compareAtPrice: 799,
    images: [
      {
        id: '5',
        url: '/images/products/belgian-linen.jpg',
        alt: 'Belgian Linen Fabric',
        width: 1200,
        height: 1600,
      },
    ],
    variants: [
      {
        id: '9',
        sku: 'LINEN-005-BEIGE',
        title: 'Natural Beige',
        colorway: { id: '12', name: 'Natural Beige', hex: '#d2b48c' },
        price: 599,
        compareAtPrice: 799,
        stockQuantity: 35,
        availability: 'in_stock',
      },
    ],
    tags: ['linen', 'european', 'breathable', 'summer'],
    certifications: ['OEKO-TEX Standard 100'],
    availability: 'in_stock',
    stockQuantity: 35,
    badge: null,
    createdAt: '2024-01-19',
    updatedAt: '2024-01-24',
  },
  {
    id: '6',
    sku: 'SATIN-006',
    title: 'Duchess Satin',
    description: 'Make your special moments unforgettable with our exquisite Duchess Satin. This heavyweight premium silk satin features a stunning high-sheen finish that captures and reflects light beautifully, creating a radiant, luminous effect. The substantial 200 GSM weight provides luxurious drape and body, perfect for structured bridal gowns, evening wear, formal dresses, and special occasion garments. Unlike regular satin, Duchess Satin maintains its shape while offering graceful movement and an elegant silhouette. The tightly woven silk fibers create a smooth, flawless surface with exceptional color depth. Ideal for creating timeless pieces that photograph beautifully and feel as luxurious as they look. Every bride\'s dream fabric, sourced from premium silk mills for uncompromising quality.',
    vendor: 'Bridal Fabrics Co.',
    collection: 'Silk',
    material: 'Silk Satin',
    gsm: 200,
    width: 140,
    colorways: [
      { id: '14', name: 'Ivory', hex: '#fffff0' },
      { id: '15', name: 'Champagne', hex: '#f7e7ce' },
    ],
    care: ['dry-clean', 'cool-iron', 'no-bleach', 'no-tumble-dry'],
    countryOfOrigin: 'China',
    unitLengthOptions: [
      { unit: 'meter', minLength: 1, maxLength: 10, increment: 0.5 },
      { unit: 'yard', minLength: 1, maxLength: 11, increment: 0.5 },
    ],
    price: 749,
    compareAtPrice: 999,
    images: [
      {
        id: '6',
        url: '/images/products/duchess-satin.jpg',
        alt: 'Duchess Satin Fabric',
        width: 1200,
        height: 1600,
      },
    ],
    variants: [
      {
        id: '10',
        sku: 'SATIN-006-IVORY',
        title: 'Ivory',
        colorway: { id: '14', name: 'Ivory', hex: '#fffff0' },
        price: 749,
        compareAtPrice: 999,
        stockQuantity: 22,
        availability: 'in_stock',
      },
    ],
    tags: ['satin', 'bridal', 'luxury', 'formal'],
    certifications: ['OEKO-TEX Standard 100'],
    availability: 'in_stock',
    stockQuantity: 22,
    badge: null,
    createdAt: '2024-01-20',
    updatedAt: '2024-01-25',
  },
  {
    id: '7',
    sku: 'WOOL-007',
    title: 'Fine Merino Wool',
    description: 'Elevate your tailoring with our Fine Merino Wool, sourced from the Scottish Highlands where tradition meets excellence. This premium wool blend features ultra-fine merino fibers known for exceptional softness and natural temperature regulation. The 250 GSM weight provides the perfect substance for structured tailoring while remaining surprisingly lightweight and comfortable. Ideal for bespoke suits, formal blazers, winter coats, trousers, and elegant skirts. The natural elasticity ensures garments retain their shape and resist wrinkles, while the breathable fibers wick moisture and regulate body temperature. The subtle natural sheen adds sophistication without being overly formal. Woolmark certified for quality assurance. This is the fabric of choice for discerning tailors and fashion houses worldwide, offering unparalleled comfort and timeless style.',
    vendor: 'Wool Masters Ltd.',
    collection: 'Wool',
    material: 'Wool',
    gsm: 250,
    width: 150,
    colorways: [
      { id: '16', name: 'Charcoal Gray', hex: '#36454f' },
      { id: '17', name: 'Navy Blue', hex: '#000080' },
    ],
    care: ['dry-clean-only', 'no-iron', 'no-bleach', 'no-tumble-dry'],
    countryOfOrigin: 'Scotland',
    unitLengthOptions: [
      { unit: 'meter', minLength: 1, maxLength: 10, increment: 0.5 },
      { unit: 'yard', minLength: 1, maxLength: 11, increment: 0.5 },
    ],
    price: 699,
    compareAtPrice: 899,
    images: [
      {
        id: '7',
        url: '/images/products/merino-wool.jpg',
        alt: 'Fine Merino Wool Fabric',
        width: 1200,
        height: 1600,
      },
    ],
    variants: [
      {
        id: '11',
        sku: 'WOOL-007-GRAY',
        title: 'Charcoal Gray',
        colorway: { id: '16', name: 'Charcoal Gray', hex: '#36454f' },
        price: 699,
        compareAtPrice: 899,
        stockQuantity: 18,
        availability: 'in_stock',
      },
    ],
    tags: ['wool', 'merino', 'tailoring', 'winter'],
    certifications: ['Woolmark Certified'],
    availability: 'in_stock',
    stockQuantity: 18,
    badge: null,
    createdAt: '2024-01-21',
    updatedAt: '2024-01-26',
  },
  {
    id: '8',
    sku: 'BROCADE-008',
    title: 'Golden Brocade',
    description: 'Transform ordinary occasions into extraordinary celebrations with our magnificent Golden Brocade. This luxurious silk brocade features richly woven metallic threads creating intricate traditional patterns that shimmer and dance in the light. At 220 GSM, this substantial fabric offers both structure and elegance, perfect for bridal wear, festive lehengas, sherwanis, ceremonial drapes, and premium home décor. The raised jacquard weave creates stunning three-dimensional patterns, while genuine zari (metallic thread) work adds authentic opulence. Each meter is a work of art, handcrafted by master weavers using techniques passed down through centuries. The combination of pure silk base and metallic embellishments creates unmatched visual richness. Handloom Mark certified, supporting India\'s rich textile heritage. Make a grand statement at weddings, festivals, and special celebrations.',
    vendor: 'Heritage Textiles',
    collection: 'Festive',
    material: 'Silk Brocade',
    gsm: 220,
    width: 110,
    colorways: [
      { id: '18', name: 'Gold & Red', hex: '#ffd700' },
      { id: '19', name: 'Silver & Purple', hex: '#c0c0c0' },
    ],
    care: ['dry-clean', 'cool-iron', 'no-bleach', 'no-tumble-dry'],
    countryOfOrigin: 'India',
    unitLengthOptions: [
      { unit: 'meter', minLength: 1, maxLength: 8, increment: 0.5 },
      { unit: 'yard', minLength: 1, maxLength: 9, increment: 0.5 },
    ],
    price: 899,
    compareAtPrice: 1199,
    images: [
      {
        id: '8',
        url: '/images/products/golden-brocade.jpg',
        alt: 'Golden Brocade Fabric',
        width: 1200,
        height: 1600,
      },
    ],
    variants: [
      {
        id: '12',
        sku: 'BROCADE-008-GOLD',
        title: 'Gold & Red',
        colorway: { id: '18', name: 'Gold & Red', hex: '#ffd700' },
        price: 899,
        compareAtPrice: 1199,
        stockQuantity: 10,
        availability: 'low_stock',
      },
    ],
    tags: ['brocade', 'festive', 'metallic', 'traditional'],
    certifications: ['Handloom Mark'],
    availability: 'low_stock',
    stockQuantity: 10,
    badge: null,
    createdAt: '2024-01-22',
    updatedAt: '2024-01-27',
  },
];

export async function GET(
  request: Request,
  { params }: { params: { id: string } }
) {
  const product = mockProducts.find((p) => p.id === params.id);

  if (!product) {
    return NextResponse.json({ error: 'Product not found' }, { status: 404 });
  }

  return NextResponse.json(product);
}

